spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blackjack_dev
    username: root
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack_dev
      database: blackjack_dev

  main:
    allow-bean-definition-overriding: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: DEBUG
    com.blackjack: DEBUG