spring:
  datasource:
    url: jdbc:h2:mem:db_test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack_test
      database: blackjack_test

logging:
  level:
    root: WARN