spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack_db?sslMode=DISABLED
    username: root
    password: 123

  data:
    mongodb:
      uri: mongodb://localhost:27017/blackjack_db

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true